# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.7-alpine

before_script:
  - apk add --update --no-cache postgresql-client
  - apk add --update --no-cache --virtual .tmp-build-deps \
    gcc libc-dev linux-headers postgresql-dev
  - pip install -r requirements.txt
  - apk del .tmp-build-deps
  - cd app

test:
  script:
    - python manage.py test && flake8
